version: 2.1

commands:
  install_dependencies:
    description: "Install dependencies"
    steps:
      - run: sudo pip install tox

jobs:
  test37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - install_dependencies
      - run:
          name: "Run tests"
          command: |
            tox -e py37
  test36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - install_dependencies
      - run:
          name: "Run tests"
          command: |
            tox -e py36
  test35:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - install_dependencies
      - run:
          name: "Run tests"
          command: |
            tox -e py35

workflows:
  version: 2
  build:
    jobs:
      - test37
      - test36
      - test35
