version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install
          command: |
            poetry install
      - run:
          name: Lint
          command: |
            poetry run flake8 humanice
      - run:
          name: "Test and Coverage"
          command: |
            poetry run coverage run --branch --source humanice -m pytest
            poetry run codecov -t "${CODECOV_TOKEN}"

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Publish
          command: |
            poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

workflows:
    version: 2

    test-workflow:
      jobs:
        - test

    deploy-workflow:
      jobs:
        - test:
            filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/
        - deploy:
            requires:
              - test
            filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*/
              branches:
                ignore: /.*/
